# Generated by Django 4.1.4 on 2022-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0002_alter_pessoa_cidade_alter_pessoa_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentos',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
