# Generated by Django 4.1.4 on 2023-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0005_atendimentos_tipoconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentos',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
